name: TotalOpnessMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: ${tfm.build.version}
description: A Gift for Fionn123
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, Essentials]
authors: [Madgeek1450, Prozza, FireCrystal12]

# plugin.yml is no longer used to define commands.
