name: TotalOpnessMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 1.0
description: A Gift for Fionn123
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Madgeek1450, Prozza, FireCrystal12]

# plugin.yml is no longer used to define commands.
